# Metody Sztucznej Inteligencji w Cyberbezpieczeństwie
# Wykrywanie ataków DDOS - klasyfikacja binarna 

## Dataset: CIC-DDos2019

## Wczytanie zależności

In [16]:
import os

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    roc_auc_score,
    roc_curve,
    f1_score,
    precision_score,
    recall_score
)

from imblearn.over_sampling import SMOTE

## Wczytanie datnych z katalogów i połączenie w jeden dataset
### Osobny dataset dla danych treningowych oraz testowych

In [4]:
TRAIN_DATASET_PATH = "../dataset/01-12"
TEST_DATASET_PATH = "../dataset/03-11"

def load_data(folder_path, max_rows_per_file=None):
    dfs = []
    for file in os.listdir(folder_path):
        if file.endswith(".csv"):
            file_path = os.path.join(folder_path, file)
            #print(f"Znaleziono plik: {file_path}")
            try:
                temp_df = pd.read_csv(file_path, nrows=max_rows_per_file)
                dfs.append(temp_df)

            except Exception as e:
                print(f"Error loading {file}: {e}")

    df = pd.concat(dfs, ignore_index=True)
    return df

train_df = load_data(TRAIN_DATASET_PATH, max_rows_per_file=50000)
test_df = load_data(TEST_DATASET_PATH, max_rows_per_file=50000)

C:\Users\kradl\AppData\Local\Temp\ipykernel_6540\348239630.py:11: DtypeWarning: Columns (0: SimillarHTTP) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path, nrows=max_rows_per_file)

In [ ]:
print(train_df.shape)
train_df.info()
train_df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 88 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Unnamed: 0                    550000 non-null  int64
 1   Flow ID                       550000 non-null  str
 2    Source IP                    550000 non-null  str
 3    Source Port                  550000 non-null  int64
 4    Destination IP               550000 non-null  str
 5    Destination Port             550000 non-null  int64
 6    Protocol                     550000 non-null  int64
 7    Timestamp                    550000 non-null  str
 8    Flow Duration                550000 non-null  int64
 9    Total Fwd Packets            550000 non-null  int64
 10   Total Backward Packets       550000 non-null  int64
 11  Total Length of Fwd Packets   550000 non-null  float64
 12   Total Length of Bwd Packets  550000 non-null  float64
 13   Fwd Packet Length Max        550000 non-null  float64
 14   Fwd Packet Length Min        550000 non-null  float64
 15   Fwd Packet Length Mean       550000 non-null  float64
 16   Fwd Packet Length Std        550000 non-null  float64
 17  Bwd Packet Length Max         550000 non-null  float64
 18   Bwd Packet Length Min        550000 non-null  float64
 19   Bwd Packet Length Mean       550000 non-null  float64
 20   Bwd Packet Length Std        550000 non-null  float64
 21  Flow Bytes/s                  540510 non-null  float64
 22   Flow Packets/s               550000 non-null  float64
 23   Flow IAT Mean                550000 non-null  float64
 24   Flow IAT Std                 550000 non-null  float64
 25   Flow IAT Max                 550000 non-null  float64
 26   Flow IAT Min                 550000 non-null  float64
 27  Fwd IAT Total                 550000 non-null  float64
 28   Fwd IAT Mean                 550000 non-null  float64
 29   Fwd IAT Std                  550000 non-null  float64
 30   Fwd IAT Max                  550000 non-null  float64
 31   Fwd IAT Min                  550000 non-null  float64
 32  Bwd IAT Total                 550000 non-null  float64
 33   Bwd IAT Mean                 550000 non-null  float64
 34   Bwd IAT Std                  550000 non-null  float64
 35   Bwd IAT Max                  550000 non-null  float64
 36   Bwd IAT Min                  550000 non-null  float64
 37  Fwd PSH Flags                 550000 non-null  int64
 38   Bwd PSH Flags                550000 non-null  int64
 39   Fwd URG Flags                550000 non-null  int64
 40   Bwd URG Flags                550000 non-null  int64
 41   Fwd Header Length            550000 non-null  int64
 42   Bwd Header Length            550000 non-null  int64
 43  Fwd Packets/s                 550000 non-null  float64
 44   Bwd Packets/s                550000 non-null  float64
 45   Min Packet Length            550000 non-null  float64
 46   Max Packet Length            550000 non-null  float64
 47   Packet Length Mean           550000 non-null  float64
 48   Packet Length Std            550000 non-null  float64
 49   Packet Length Variance       550000 non-null  float64
 50  FIN Flag Count                550000 non-null  int64
 51   SYN Flag Count               550000 non-null  int64
 52   RST Flag Count               550000 non-null  int64
 53   PSH Flag Count               550000 non-null  int64
 54   ACK Flag Count               550000 non-null  int64
 55   URG Flag Count               550000 non-null  int64
 56   CWE Flag Count               550000 non-null  int64
 57   ECE Flag Count               550000 non-null  int64
 58   Down/Up Ratio                550000 non-null  float64
 59   Average Packet Size          550000 non-null  float64
 60   Avg Fwd Segment Size         550000 non-null  float64
 61   Avg Bwd Segment Size         550000 non-null  float64
 62   Fwd Header Length.1          550000 non-null  int64
 63  Fwd Avg Bytes/Bulk            550000 non-null  int64
 64   Fwd Avg Packets/Bulk         550000 non-null  int64
 65   Fwd Avg Bulk Rate            550000 non-null  int64
 66   Bwd Avg Bytes/Bulk           550000 non-null  int64
 67   Bwd Avg Packets/Bulk         550000 non-null  int64
 68  Bwd Avg Bulk Rate             550000 non-null  int64
 69  Subflow Fwd Packets           550000 non-null  int64
 70   Subflow Fwd Bytes            550000 non-null  int64
 71   Subflow Bwd Packets          550000 non-null  int64
 72   Subflow Bwd Bytes            550000 non-null  int64
 73  Init_Win_bytes_forward        550000 non-null  int64
 74   Init_Win_bytes_backward      550000 non-null  int64
 75   act_data_pkt_fwd             550000 non-null  int64
 76   min_seg_size_forward         550000 non-null  int64
 77  Active Mean                   550000 non-null  float64
 78   Active Std                   550000 non-null  float64
 79   Active Max                   550000 non-null  float64
 80   Active Min                   550000 non-null  float64
 81  Idle Mean                     550000 non-null  float64
 82   Idle Std                     550000 non-null  float64
 83   Idle Max                     550000 non-null  float64
 84   Idle Min                     550000 non-null  float64
 85  SimillarHTTP                  550000 non-null  object
 86   Inbound                      550000 non-null  int64
 87   Label                        550000 non-null  str
dtypes: float64(45), int64(37), object(1), str(5)
memory usage: 369.3+ MB

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,425,172.16.0.5-192.168.50.1-634-60495-17,172.16.0.5,634,192.168.50.1,60495,17,2018-12-01 10:51:39.813448,28415,97,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
1,430,172.16.0.5-192.168.50.1-60495-634-17,192.168.50.1,634,172.16.0.5,60495,17,2018-12-01 10:51:39.820842,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,DrDoS_DNS
2,1654,172.16.0.5-192.168.50.1-634-46391-17,172.16.0.5,634,192.168.50.1,46391,17,2018-12-01 10:51:39.852499,48549,200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
3,2927,172.16.0.5-192.168.50.1-634-11894-17,172.16.0.5,634,192.168.50.1,11894,17,2018-12-01 10:51:39.890213,48337,200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
4,694,172.16.0.5-192.168.50.1-634-27878-17,172.16.0.5,634,192.168.50.1,27878,17,2018-12-01 10:51:39.941151,32026,200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS

In [ ]:
print(test_df.shape)
test_df.info()
test_df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 350000 entries, 0 to 349999
Data columns (total 88 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Unnamed: 0                    350000 non-null  int64
 1   Flow ID                       350000 non-null  str
 2    Source IP                    350000 non-null  str
 3    Source Port                  350000 non-null  int64
 4    Destination IP               350000 non-null  str
 5    Destination Port             350000 non-null  int64
 6    Protocol                     350000 non-null  int64
 7    Timestamp                    350000 non-null  str
 8    Flow Duration                350000 non-null  int64
 9    Total Fwd Packets            350000 non-null  int64
 10   Total Backward Packets       350000 non-null  int64
 11  Total Length of Fwd Packets   350000 non-null  float64
 12   Total Length of Bwd Packets  350000 non-null  float64
 13   Fwd Packet Length Max        350000 non-null  float64
 14   Fwd Packet Length Min        350000 non-null  float64
 15   Fwd Packet Length Mean       350000 non-null  float64
 16   Fwd Packet Length Std        350000 non-null  float64
 17  Bwd Packet Length Max         350000 non-null  float64
 18   Bwd Packet Length Min        350000 non-null  float64
 19   Bwd Packet Length Mean       350000 non-null  float64
 20   Bwd Packet Length Std        350000 non-null  float64
 21  Flow Bytes/s                  349994 non-null  float64
 22   Flow Packets/s               350000 non-null  float64
 23   Flow IAT Mean                350000 non-null  float64
 24   Flow IAT Std                 350000 non-null  float64
 25   Flow IAT Max                 350000 non-null  float64
 26   Flow IAT Min                 350000 non-null  float64
 27  Fwd IAT Total                 350000 non-null  float64
 28   Fwd IAT Mean                 350000 non-null  float64
 29   Fwd IAT Std                  350000 non-null  float64
 30   Fwd IAT Max                  350000 non-null  float64
 31   Fwd IAT Min                  350000 non-null  float64
 32  Bwd IAT Total                 350000 non-null  float64
 33   Bwd IAT Mean                 350000 non-null  float64
 34   Bwd IAT Std                  350000 non-null  float64
 35   Bwd IAT Max                  350000 non-null  float64
 36   Bwd IAT Min                  350000 non-null  float64
 37  Fwd PSH Flags                 350000 non-null  int64
 38   Bwd PSH Flags                350000 non-null  int64
 39   Fwd URG Flags                350000 non-null  int64
 40   Bwd URG Flags                350000 non-null  int64
 41   Fwd Header Length            350000 non-null  int64
 42   Bwd Header Length            350000 non-null  int64
 43  Fwd Packets/s                 350000 non-null  float64
 44   Bwd Packets/s                350000 non-null  float64
 45   Min Packet Length            350000 non-null  float64
 46   Max Packet Length            350000 non-null  float64
 47   Packet Length Mean           350000 non-null  float64
 48   Packet Length Std            350000 non-null  float64
 49   Packet Length Variance       350000 non-null  float64
 50  FIN Flag Count                350000 non-null  int64
 51   SYN Flag Count               350000 non-null  int64
 52   RST Flag Count               350000 non-null  int64
 53   PSH Flag Count               350000 non-null  int64
 54   ACK Flag Count               350000 non-null  int64
 55   URG Flag Count               350000 non-null  int64
 56   CWE Flag Count               350000 non-null  int64
 57   ECE Flag Count               350000 non-null  int64
 58   Down/Up Ratio                350000 non-null  float64
 59   Average Packet Size          350000 non-null  float64
 60   Avg Fwd Segment Size         350000 non-null  float64
 61   Avg Bwd Segment Size         350000 non-null  float64
 62   Fwd Header Length.1          350000 non-null  int64
 63  Fwd Avg Bytes/Bulk            350000 non-null  int64
 64   Fwd Avg Packets/Bulk         350000 non-null  int64
 65   Fwd Avg Bulk Rate            350000 non-null  int64
 66   Bwd Avg Bytes/Bulk           350000 non-null  int64
 67   Bwd Avg Packets/Bulk         350000 non-null  int64
 68  Bwd Avg Bulk Rate             350000 non-null  int64
 69  Subflow Fwd Packets           350000 non-null  int64
 70   Subflow Fwd Bytes            350000 non-null  int64
 71   Subflow Bwd Packets          350000 non-null  int64
 72   Subflow Bwd Bytes            350000 non-null  int64
 73  Init_Win_bytes_forward        350000 non-null  int64
 74   Init_Win_bytes_backward      350000 non-null  int64
 75   act_data_pkt_fwd             350000 non-null  int64
 76   min_seg_size_forward         350000 non-null  int64
 77  Active Mean                   350000 non-null  float64
 78   Active Std                   350000 non-null  float64
 79   Active Max                   350000 non-null  float64
 80   Active Min                   350000 non-null  float64
 81  Idle Mean                     350000 non-null  float64
 82   Idle Std                     350000 non-null  float64
 83   Idle Max                     350000 non-null  float64
 84   Idle Min                     350000 non-null  float64
 85  SimillarHTTP                  350000 non-null  object
 86   Inbound                      350000 non-null  int64
 87   Label                        350000 non-null  str
dtypes: float64(45), int64(37), object(1), str(5)
memory usage: 235.0+ MB

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,13605,172.16.0.5-192.168.50.4-870-2908-17,172.16.0.5,870,192.168.50.4,2908,17,2018-11-03 10:09:00.565557,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
1,62631,172.16.0.5-192.168.50.4-871-53796-17,172.16.0.5,871,192.168.50.4,53796,17,2018-11-03 10:09:00.565559,48,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
2,143869,172.16.0.5-192.168.50.4-648-40660-17,172.16.0.5,648,192.168.50.4,40660,17,2018-11-03 10:09:00.565608,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
3,16171,172.16.0.5-192.168.50.4-872-54308-17,172.16.0.5,872,192.168.50.4,54308,17,2018-11-03 10:09:00.565993,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
4,80845,172.16.0.5-192.168.50.4-873-40653-17,172.16.0.5,873,192.168.50.4,40653,17,2018-11-03 10:09:00.565994,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS

## Preprocessing

In [9]:
def clean(df):
    df.columns = df.columns.str.strip()

    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    return df


train_df = clean(train_df)
test_df = clean(test_df)

## Etykiety 
### zmienna docelowa
Label = 0 -> normalny ruch
Label = 1 -> atak DDoS

In [ ]:
train_df['Label'] = train_df['Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
test_df['Label'] = test_df['Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)

print(train_df['Label'].value_counts())
print(test_df['Label'].value_counts())

['Unnamed: 0', 'Flow ID', 'Source IP', 'Source Port', 'Destination IP', 'Destination Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'SimillarHTTP', 'Inbound', 'Label']
Label
1    531741
Name: count, dtype: int64
Label
1    336248
Name: count, dtype: int64

## Atrybuty
Oddzielono dane wejściowe od etykiet klas oraz usunięto kolumny tekstowe i identyfikacyjne

In [17]:
X_train = train_df.drop(columns=['Label'])
y_train = train_df['Label']

X_test = test_df.drop(columns=['Label'])
y_test = test_df['Label']


# nienumeryczne
non_numeric = X_train.select_dtypes(exclude=[np.number]).columns

X_train = X_train.drop(columns=non_numeric)
X_test = X_test.drop(columns=non_numeric)

## SMOTE
### Balansowanie klas w zbiorze danych

In [18]:
smote = SMOTE(random_state=42)

X_train, y_train = smote.fit_resample(X_train, y_train)

print(pd.Series(y_train).value_counts())

ValueError: The target 'y' needs to have more than 1 class. Got 1 class instead

## MODEL
### RandomForestClassifier

In [19]:
model = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

## Trenowanie modelu

In [20]:
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

## Testowanie modelu

In [21]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# Raport
print("\nCLASSIFICATION:\n")
print(classification_report(y_test, y_pred))

print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))

IndexError: index 1 is out of bounds for axis 1 with size 1